[package]
name = "entities"
version = "0.1.0"
edition = "2021"



[lib]
name = "entities"
path = "src/mod.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
sea-orm = { version = "0.12", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] } 