//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "block_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub chain_id: String,
    pub block_number: i32,
    pub block_slot: i32,
    #[sea_orm(column_type = "Text")]
    pub block_hash: String,
    pub block_time: i32,
    #[sea_orm(column_type = "Text")]
    pub block_address: String,
    #[sea_orm(column_type = "Text")]
    pub block_memo: String,
    #[sea_orm(column_type = "Text")]
    pub parent_hash: String,
    pub nonce: i32,
    pub difficulty: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
