//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tx_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub block_id: i32,
    #[sea_orm(column_type = "Text")]
    pub tx_hash: String,
    pub tx_type: i32,
    #[sea_orm(column_type = "Text")]
    pub tx_status: String,
    pub tx_amount: i32,
    pub tx_fee: i32,
    #[sea_orm(column_type = "Text")]
    pub tx_time: String,
    #[sea_orm(column_type = "Text")]
    pub from_address: String,
    #[sea_orm(column_type = "Text")]
    pub to_address: String,
    #[sea_orm(column_type = "Text")]
    pub tx_memo: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
